config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  devise_for :users
  resources :charges, :customers

  get 'home' => 'welcome#index', as: 'home'
  get 'about' => 'welcome#about', as: 'about'
  get 'contact' => 'welcome#contact', as: 'contact'

  root 'welcome#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
  validates :address_line_1, presence: true
  validates :address_city, presence: true
  validates :address_state, presence: true
  validates :address_zip, presence: true
  validates :recipient_address_line_1, presence: true
  validates :recipient_address_city, presence: true
  validates :recipient_address_state, presence: true
  validates :recipient_address_zip, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :address
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @user = current_user
    @address = Address.new(address_params)
    @address.user_id = current_user.id if current_user

    respond_to do |format|
      if @address.save
        format.html { redirect_to new_charge_path, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:full_name, :address_line_1, :address_line_2, :address_city, :address_state, :address_zip, :user_id, :recipient_full_name, :recipient_address_line_1, :recipient_address_line_2, :recipient_address_city, :recipient_address_state, :recipient_address_zip,)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

def new
end

def create
  # Amount in cents
  @amount = 5000

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Wine pEaring customer',
    :currency    => 'usd'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
  def index
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/addresses/_form.html.erb
<div class="jumbotron">
<% @user = current_user %>
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
Sender's information
  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :address_line_1 %><br>
    <%= f.text_field :address_line_1 %>
  </div>
  <div class="field">
    <%= f.label :address_line_2 %><br>
    <%= f.text_field :address_line_2 %>
  </div>
  <div class="field">
    <%= f.label :address_city %><br>
    <%= f.text_field :address_city %>
  </div>
  <div class="field">
    <%= f.label :address_state %><br>
    <%= f.text_field :address_state %>
  </div>
  <div class="field">
    <%= f.label :address_zip %><br>
    <%= f.text_field :address_zip %>
  </div>

Recipient's information
  <div class="field">
    <%= f.label :recipient_full_name %><br>
    <%= f.text_field :recipient_full_name %>
  </div>
  <div class="field">
    <%= f.label :recipient_address_line_1 %><br>
    <%= f.text_field :recipient_address_line_1 %>
  </div>
  <div class="field">
    <%= f.label :recipient_address_line_2 %><br>
    <%= f.text_field :recipient_address_line_2 %>
  </div>
  <div class="field">
    <%= f.label :recipient_address_city %><br>
    <%= f.text_field :recipient_address_city %>
  </div>
  <div class="field">
    <%= f.label :recipient_address_state %><br>
    <%= f.text_field :recipient_address_state %>
  </div>
  <div class="field">
    <%= f.label :recipient_address_zip %><br>
    <%= f.text_field :recipient_address_zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/addresses/edit.html.erb
<div class="jumbotron">
<h1>Editing Address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>
</div>

app/views/addresses/index.html.erb
<div class="jumbotron">
<p id="notice"><%= notice %></p>

<h1>Listing Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Address line 1</th>
      <th>Address line 2</th>
      <th>Address city</th>
      <th>Address state</th>
      <th>Address zip</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.full_name %></td>
        <td><%= address.address_line_1 %></td>
        <td><%= address.address_line_2 %></td>
        <td><%= address.address_city %></td>
        <td><%= address.address_state %></td>
        <td><%= address.address_zip %></td>
        <td><%= address.user %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>
</div>

app/views/addresses/new.html.erb
<div class="jumbotron">
<h1>New Address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>
</div>

app/views/addresses/show.html.erb
<div class="jumbotron">
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @address.full_name %>
</p>

<p>
  <strong>Address line 1:</strong>
  <%= @address.address_line_1 %>
</p>

<p>
  <strong>Address line 2:</strong>
  <%= @address.address_line_2 %>
</p>

<p>
  <strong>Address city:</strong>
  <%= @address.address_city %>
</p>

<p>
  <strong>Address state:</strong>
  <%= @address.address_state %>
</p>

<p>
  <strong>Address zip:</strong>
  <%= @address.address_zip %>
</p>

<p>
  <strong>User:</strong>
  <%= @address.user %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>
</div>

app/views/charges/create.html.erb
<div class="jumbotron">
	<h2>Thanks, you paid <strong>$50.00</strong>! You will receive an email shortly to confirm your order.</h2>
</div>

app/views/charges/new.html.erb
<div class="jumbotron">
  <%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $50.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="5000"
          data-locale="auto"></script>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WinepEaring</title>
  <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
          	<% if current_user %>
          	Currently logged in as <%= current_user.email %>. Not you? <li role="presentation"><%= link_to 'Log out', destroy_user_session_path %></li><br/>          	
	<% else %>
			<li role="presentation"><%= link_to 'Log in', new_user_session_path %></li>
			<li role="presentation"> <%= link_to 'Sign up', new_user_registration_path %> </li>
	<% end %>
            <li role="presentation"><%= link_to 'Home', home_path %></li>
            <li role="presentation"><%= link_to 'About', home_path %></li>
            <li role="presentation"><%= link_to 'Contact', home_path %></li>
          </ul>
        </nav>
        <h3 class="text-muted">Wine pEaring</h3>
      </div>


<%= yield %>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
	  <title>WinepEaring</title>
  <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
          	<% if current_user %>
          	Currently logged in as <%= current_user.email %>. Not you? <li role="presentation"><%= link_to 'Log out', destroy_user_session_path %></li><br/>          	
	<% else %>
			<li role="presentation"><%= link_to 'Log in', new_user_session_path %></li>
			<li role="presentation"> <%= link_to 'Sign up', new_user_registration_path %> </li>
	<% end %>
            <li role="presentation"><%= link_to 'Home', home_path %></li>
            <li role="presentation"><%= link_to 'About', about_path %></li>
            <li role="presentation"><%= link_to 'Contact', contact_path %></li>
          </ul>
        </nav>
        <h3 class="text-muted">Wine pEaring</h3>
      </div>
  <%= yield %>
</body>
</html>

app/views/welcome/about.html.erb
      <div class="row marketing">
        <div class="col-lg-12">
          <h4>Our Basis.</h4>
          <p>Wine stimiulates taste, scent, touch, and sight. As a self proclaimed audiophile and wine appreciator, I believe that with a little attention to detail the gap is easily bridged to combine all 5 senses in one harmonious experience.</p>

          <h4>What we do.</h4>
          <p>Every month we will ship to you and your loved one near or far a package containing a bottle of wine and a playlist specifically curated to compliment that bottle. Throw on the album, pop the cork and enjoy wine like you never have before. The music's not bad either ;).</p>

          <h4>There's more!</h4>
          <p>Why experience this alone? With our one of the kind service you can share this experience with your loved ones wherever they live! One subscription includes two shipments, one to you and one to the recipient of your choosing. They are scheduled to arrive the same day so you can phone, facetime, text, email, tweet, instagram, facebook, or snapchat the experience with your daughter, son, grandchildren, parents, grandparents, and even just your friends!</p>

       </div>

      </div>

app/views/welcome/contact.html.erb
      <div class="row marketing">
        <div class="col-lg-12">
          <h4>Email</h4>
          <p>brian.mcauley.rails@gmail.com</p>

          <h4>Phone</h4>
          <p>425-445-1106</p>

       </div>

      </div>

app/views/welcome/index.html.erb
      <div class="jumbotron">
        <h1>Wine pEaring</h1>
        <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-lg btn-success" 
        	<% if current_user %>
        	href="/home"
        	<% else %>
        	href="/users/sign_up" 
        	<% end %>
        	role="button">Sign up today</a></p>
      </div>

      <div class="row marketing">
        <div class="col-lg-6">
          <h4>Subheading</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Subheading</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>

        <div class="col-lg-6">
          <h4>Subheading</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Subheading</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>
      </div>

      <footer class="footer">
        <p>&copy; 2015 Company, Inc.</p>
      </footer>

    </div> <!-- /container -->